/**
 * Deployment addresses service
 *
 * Loads pre-deployed contract addresses from deployment files.
 * - Local: .deployments.local.json (generated by `make devnet-up`)
 * - Devnet: .deployments.devnet.json (generated by deploy-devnet script)
 */

import type { Address, AztecAddress } from "@aztec-aave-wrapper/shared";
import { getCurrentNetwork, type NetworkId } from "./network.js";

/**
 * Raw deployment file structure (matches deploy scripts output)
 */
interface DeploymentsFile {
  l1: {
    mockUsdc: string;
    mockLendingPool: string;
    tokenPortal: string;
    portal: string;
    faucet: string;
  };
  l2: {
    bridgedToken: string;
    aaveWrapper: string;
  };
  config: {
    l1ChainId: number;
    deployedAt: string;
    network?: string;
  };
}

/**
 * Parsed deployment addresses for app consumption
 */
export interface DeploymentAddresses {
  l1: {
    portal: Address;
    tokenPortal: Address;
    mockUsdc: Address;
    mockLendingPool: Address;
    faucet: Address;
  };
  l2: {
    bridgedToken: AztecAddress;
    aaveWrapper: AztecAddress;
  };
  config: {
    l1ChainId: number;
    deployedAt: Date;
    network?: string;
  };
}

/**
 * Fetch and parse deployment addresses for the current network
 *
 * @throws Error if file cannot be fetched or parsed
 */
export async function fetchDeploymentAddresses(): Promise<DeploymentAddresses> {
  const network = getCurrentNetwork();
  return fetchDeploymentAddressesForNetwork(network.id);
}

/**
 * Fetch and parse deployment addresses for a specific network
 *
 * @param networkId - Network to fetch deployments for
 * @throws Error if file cannot be fetched or parsed
 */
export async function fetchDeploymentAddressesForNetwork(
  networkId: NetworkId
): Promise<DeploymentAddresses> {
  const deploymentsFile =
    networkId === "local" ? "/.deployments.local.json" : "/.deployments.devnet.json";

  const response = await fetch(deploymentsFile);

  if (!response.ok) {
    const hint =
      networkId === "local"
        ? "Make sure local devnet is running (make devnet-up) and contracts are deployed."
        : "Make sure contracts are deployed to devnet (scripts/deploy-devnet.ts).";

    throw new Error(
      `Failed to fetch deployment addresses for ${networkId}: ${response.status} ${response.statusText}. ${hint}`
    );
  }

  const data: DeploymentsFile = await response.json();

  return {
    l1: {
      portal: data.l1.portal as Address,
      tokenPortal: data.l1.tokenPortal as Address,
      mockUsdc: data.l1.mockUsdc as Address,
      mockLendingPool: data.l1.mockLendingPool as Address,
      faucet: data.l1.faucet as Address,
    },
    l2: {
      bridgedToken: data.l2.bridgedToken as AztecAddress,
      aaveWrapper: data.l2.aaveWrapper as AztecAddress,
    },
    config: {
      l1ChainId: data.config.l1ChainId,
      deployedAt: new Date(data.config.deployedAt),
      network: data.config.network,
    },
  };
}
