/**
 * Deployment addresses service
 *
 * Loads pre-deployed contract addresses from .deployments.local.json
 * Generated by `make devnet-up` deployment script.
 */

import type { Address, AztecAddress } from "@aztec-aave-wrapper/shared";

/**
 * Raw deployment file structure (matches deploy-local.ts output)
 */
interface DeploymentsFile {
  l1: {
    mockUsdc: string;
    mockLendingPool: string;
    portal: string;
  };
  l2: {
    aaveWrapper: string;
  };
  config: {
    l1ChainId: number;
    deployedAt: string;
  };
}

/**
 * Parsed deployment addresses for app consumption
 */
export interface DeploymentAddresses {
  l1: {
    portal: Address;
    mockUsdc: Address;
    mockLendingPool: Address;
  };
  l2: {
    aaveWrapper: AztecAddress;
  };
  config: {
    l1ChainId: number;
    deployedAt: Date;
  };
}

/**
 * Fetch and parse deployment addresses from .deployments.local.json
 *
 * @throws Error if file cannot be fetched or parsed
 */
export async function fetchDeploymentAddresses(): Promise<DeploymentAddresses> {
  const response = await fetch("/.deployments.local.json");

  if (!response.ok) {
    throw new Error(
      `Failed to fetch deployment addresses: ${response.status} ${response.statusText}. ` +
        "Make sure devnet is running (make devnet-up) and contracts are deployed."
    );
  }

  const data: DeploymentsFile = await response.json();

  return {
    l1: {
      portal: data.l1.portal as Address,
      mockUsdc: data.l1.mockUsdc as Address,
      mockLendingPool: data.l1.mockLendingPool as Address,
    },
    l2: {
      aaveWrapper: data.l2.aaveWrapper as AztecAddress,
    },
    config: {
      l1ChainId: data.config.l1ChainId,
      deployedAt: new Date(data.config.deployedAt),
    },
  };
}
